version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    depends_on:
      - postgres  
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - 5050:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment_db
    restart: always
