version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    depends_on:
      - db  

  db:
    image: postgres:latest  
    environment:
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: oracle  
      POSTGRES_PASSWORD: hmm123  
    ports:
      - "3333:5432"  
